version: "3.7"

services:
  app:
    build:
      context: .
      args:
        - NODE_AUTH_TOKEN
    environment:
      - MICRO_WEBSOCKET_TOP_REDIRECT
    volumes:
      - $MICRO_WEBSOCKET_SOCKET_DIRECTORY_PATH:/socket/
    restart: always
